/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss;

/**
 *
 * @author royn
 */
public class LandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public LandingJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccountCatalog = new javax.swing.JButton();
        btnOrderCatalog = new javax.swing.JButton();
        btnSalesPerformance = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        brnProductCatalog = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAccountCatalog.setText("Account Catalog");
        add(btnAccountCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 250, 80));

        btnOrderCatalog.setText("Order Catalog");
        add(btnOrderCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 250, 80));

        btnSalesPerformance.setText("Sales Performance");
        add(btnSalesPerformance, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 250, 80));

        btnSupplier.setText("Supplier");
        add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 250, 80));

        brnProductCatalog.setText("Product Catalog");
        add(brnProductCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 250, 80));

        btnSales.setText("Sales");
        add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 250, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnProductCatalog;
    private javax.swing.JButton btnAccountCatalog;
    private javax.swing.JButton btnOrderCatalog;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnSalesPerformance;
    private javax.swing.JButton btnSupplier;
    // End of variables declaration//GEN-END:variables
}
