/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss;

import UserInterface.Boss.Account.ManageAccountJPanel;
import UserInterface.Boss.Market.ManageMarketJPanel;
import UserInterface.Boss.Supplier.ManageSupplierJPanel;
import UserInterface.Components.HasTitle;
import UserInterface.Components.ParentUI;
import biz.Components.Boss;

/**
 *
 * @author royn
 */
public class LandingJPanel extends javax.swing.JPanel implements HasTitle {
    private ParentUI parentUI;
    private Boss boss;
    
    /**
     * Creates new form NewJPanel
     */
    public LandingJPanel(ParentUI parentUI, Boss boss) {
        initComponents();
        this.parentUI = parentUI;
        this.boss = boss;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccountCatalog = new javax.swing.JButton();
        btnOrderCatalog = new javax.swing.JButton();
        btnMarket = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        brnProductCatalog = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnSalesPerformance = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAccountCatalog.setText("Account Catalog");
        btnAccountCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountCatalogActionPerformed(evt);
            }
        });
        add(btnAccountCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 230, 70));

        btnOrderCatalog.setText("Order Catalog");
        add(btnOrderCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 70));

        btnMarket.setText("Market");
        btnMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarketActionPerformed(evt);
            }
        });
        add(btnMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 230, 70));

        btnSupplier.setText("Supplier");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 70));

        brnProductCatalog.setText("Product Catalog");
        add(brnProductCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 230, 70));

        btnSales.setText("Sales");
        add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 230, 70));

        btnSalesPerformance.setText("Sales Performance");
        add(btnSalesPerformance, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 230, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountCatalogActionPerformed
        this.parentUI.pushComponent(new ManageAccountJPanel(parentUI));
    }//GEN-LAST:event_btnAccountCatalogActionPerformed

    private void btnMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarketActionPerformed
        // TODO add your handling code here:
        this.parentUI.pushComponent(new ManageMarketJPanel(parentUI));
    }//GEN-LAST:event_btnMarketActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        // TODO add your handling code here:
        this.parentUI.pushComponent(new ManageSupplierJPanel(parentUI));
    }//GEN-LAST:event_btnSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnProductCatalog;
    private javax.swing.JButton btnAccountCatalog;
    private javax.swing.JButton btnMarket;
    private javax.swing.JButton btnOrderCatalog;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnSalesPerformance;
    private javax.swing.JButton btnSupplier;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return String.format("Hello, %s", boss);
    }
}
