/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss.Sales;

import UserInterface.Components.HasTitle;
import UserInterface.Components.ParentUI;
import UserInterface.Components.TablePopulatable;
import biz.Components.Business;
import biz.Components.Order;
import biz.Components.SalesPerson;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author royn
 */
public class ManageSalesPersonJPanel extends javax.swing.JPanel implements HasTitle, TablePopulatable<SalesPerson> {
    private ParentUI parent;
    
    /**
     * Creates new form ManageSalesPersonJPanel
     */
    public ManageSalesPersonJPanel(ParentUI parent) {
        initComponents();
        this.parent = parent;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalesPerson = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnView1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSalesPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full Name", "username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSalesPerson);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 660, 580));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 200, 40));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 200, 40));

        btnDeleteCustomer.setText("Delete");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });
        add(btnDeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 200, 40));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 200, 40));

        btnView1.setText("<<Export");
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });
        add(btnView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        final String salesPersonName = JOptionPane.showInputDialog(this, "Please input the name of Sales Person you want to find");
        if (salesPersonName == null){
            return;
        }else{
            ArrayList<SalesPerson> salesPersonList = Business.getInstance().getSalesPersonCatalog().findElements((s -> s.toString().equals(salesPersonName)));
            populateTable(salesPersonList);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        SalesPerson selectedSalesPerson = getSelected();
        if (selectedSalesPerson == null) {
            return;
        }else {
            this.parent.pushComponent(new UpdateSalesPersonJPanel(parent, selectedSalesPerson));
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:
        SalesPerson selectedSalesPerson = getSelected();
        if (selectedSalesPerson == null) {
            return;
        }
        
        Order order = Business.getInstance().getOrderDirectory().findElement(o -> o.getSoldBy().equals(selectedSalesPerson));
        if (order != null) {
            JOptionPane.showMessageDialog(this, "Cannot remove, this sales person has order", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        SalesPerson selected = getSelected();
        if (selected == null) {
            return;
        }
        if (removeSelected(Business.getInstance().getSalesPersonCatalog())) {
            Business.getInstance().getAccountCatalog().removeAccount(selected);
        }
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.parent.pushComponent(new AddSalesPersonJPanel(parent));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:
        toCSV();
    }//GEN-LAST:event_btnView1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalesPerson;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "Manage Sales Person";
    }

    @Override
    public JTable getTable() {
        return tblSalesPerson;
    }

    @Override
    public Object[] populateRow(SalesPerson salsPerson) {
        return new Object[]{
            salsPerson,
            salsPerson.getUsername()
        };
    }

    @Override
    public void populateTable() {
        populateTable(Business.getInstance().getSalesPersonCatalog().getElementArrayList());
    }
}
