/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss.Sales;

import UserInterface.Components.HasTitle;
import UserInterface.Components.ParentUI;
import biz.Components.Business;
import biz.Components.SalesPerson;
import javax.swing.JOptionPane;

/**
 *
 * @author hezj
 */
public class UpdateSalesPersonJPanel extends javax.swing.JPanel implements HasTitle{
    private SalesPerson salesPerson;
    private ParentUI parent;
    
    
    /**
     * Creates new form UpdateSalesPersonJPanel
     */
    public UpdateSalesPersonJPanel(ParentUI parent, SalesPerson salesPerson) {
        initComponents();
        this.salesPerson = salesPerson;
        this.parent = parent;
        
        refreshComponents();
    }
    
    public void refreshComponents(){
        txtFirstName.setText(salesPerson.getFirstName());
        txtLastName.setText(salesPerson.getLastName());
        
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Address = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        btnSave3 = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Address.setText("Last Name");
        add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 120, 30));

        jLabel6.setText("First Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 70, 30));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 170, -1));

        btnSave3.setText("Save");
        btnSave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave3ActionPerformed(evt);
            }
        });
        add(btnSave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 170, 50));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave3ActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();

        salesPerson.setFirstName(firstName);
        salesPerson.setLastName(lastName);

        JOptionPane.showMessageDialog(null, "Sales person update successfully!");
    }//GEN-LAST:event_btnSave3ActionPerformed

    @Override
    public String getTitle() {
        return "Update " + salesPerson;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton btnSave3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
