/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson;

import UserInterface.Components.ParentUI;
import biz.Components.SalesPerson;

/**
 *
 * @author royn
 */
public class LandingJPanel extends javax.swing.JPanel {
    private ParentUI parentUI;
    private SalesPerson salesPerson;
    
    /**
     * Creates new form LandingJPanel
     */
    public LandingJPanel(ParentUI parentUI, SalesPerson salesPerson) {
        initComponents();
        this.parentUI = parentUI;
        this.salesPerson = salesPerson;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrder = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrder.setText("Manage Order");
        add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 260, 110));

        btnCustomer.setText("Manage Customer");
        add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 260, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnOrder;
    // End of variables declaration//GEN-END:variables
}
