/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Components;

import biz.Components.Account;
import biz.Components.Boss;
import biz.Components.SalesPerson;
import biz.Components.Supplier;

import java.awt.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hezj
 */
public class WorkAreaParent extends javax.swing.JPanel implements ParentUI {
    private MainJFrame mainJFrame;
    private HeaderJPanel header;
    private Account account;

    /**
     * Creates new form WorkAreaParent
     */
    public WorkAreaParent(MainJFrame mainJFrame, Account account) {
        initComponents();
        this.mainJFrame = mainJFrame;
        this.account = account;

        this.add(new FooterJPanel(this), BorderLayout.PAGE_END);

        this.header = new HeaderJPanel();
        this.add(header, BorderLayout.PAGE_START);
        
        if (account instanceof Boss) {
            this.pushComponent(new UserInterface.Boss.LandingJPanel(this));
        } else if (account instanceof Supplier) {
            this.pushComponent(new UserInterface.Supplier.ManageProductJPanel(this, (Supplier) account));
        } else if (account instanceof SalesPerson) {
            this.pushComponent(new UserInterface.SalesPerson.LandingJPanel(this, (SalesPerson) account));
        } else {
            JOptionPane.showConfirmDialog(this, "Unknown Account.", "Warning", JOptionPane.WARNING_MESSAGE);
            mainJFrame.popComponent();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        containerJPanel.setLayout(new java.awt.CardLayout());
        add(containerJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setHeaderTitle(String title) {
        this.header.setTitle(title);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerJPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getContainerJPanel() {
        return containerJPanel;
    }

    @Override
    public void allComponentsPoped() {
        mainJFrame.popAllComponents();
    }

    @Override
    public void componentPoped() {
        if (containerJPanel.getComponentCount() == 0) {
            mainJFrame.popComponent();
        }
    }
}
