/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss.Market;

import UserInterface.Components.ParentUI;
import biz.Components.Market;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class UpdateMarketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateMarket
     */
    private ParentUI parent;
    private Market market;
    public UpdateMarketJPanel(ParentUI parent, Market ma) {
        initComponents();
        this.parent = parent;
        this.market = ma;
        updateComponents();
    }
    
    public void updateComponents(){
        nameTF.setText(market.getMarketName());
        valueTF.setText(String.valueOf(market.getMarketValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        valueTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTF.setText(" ");
        add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 135, -1));

        jLabel1.setText("New Market Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        valueTF.setText(" ");
        add(valueTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 135, -1));

        jLabel2.setText("New Market Value");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double val;
        try{
            val = Double.parseDouble(valueTF.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please input correct value","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        market.setMarketName(nameTF.getText());
        market.setMarketValue(val);
        
        JOptionPane.showMessageDialog(this, "Market Updated Successfully!");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField valueTF;
    // End of variables declaration//GEN-END:variables
}
