/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson.Customer;

import biz.Components.Business;
import biz.Components.Customer;
import biz.Components.Market;
import javax.swing.JOptionPane;

/**
 *
 * @author royn
 */
public class CreateCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCustomer
     */
    public CreateCustomerJPanel() {
        initComponents();
        populateMarket();
    }
    public void populateMarket(){
        cbxMarket.removeAllItems();
        for(Market ma : Business.getInstance().getMarketCatalog().getElementArrayList()){
            cbxMarket.addItem(ma);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cbxMarket = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Market");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 70, 30));

        jLabel6.setText("Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 70, 30));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 170, -1));

        cbxMarket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbxMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 170, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 170, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Market ma = (Market)cbxMarket.getSelectedItem();
        Customer c = ma.newElement();
        c.setName(txtName.getText());
        JOptionPane.showMessageDialog(null,"Great!");
        txtName.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbxMarket;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
