/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson.Customer;

import UserInterface.Components.HasTitle;
import UserInterface.Components.ParentUI;
import UserInterface.Components.TablePopulatable;
import UserInterface.SalesPerson.Order.PlaceOrUpdateOrderJpanel;
import biz.Components.Business;
import biz.Components.Customer;
import biz.Components.SalesPerson;
import javax.swing.JTable;

/**
 *
 * @author royn
 */
public class ManageCustomerJPanel extends javax.swing.JPanel implements HasTitle, TablePopulatable<Customer> {
    private ParentUI parent;
    private SalesPerson salesPerson;
    
    /**
     * Creates new form ManageCustomer
     */
    public ManageCustomerJPanel(ParentUI parent, SalesPerson salesPerson) {
        initComponents();
        this.parent = parent;
        this.salesPerson = salesPerson;
        populateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnAddCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        btnView1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Market"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 520, 421));

        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });
        add(btnAddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 220, 40));

        btnUpdateCustomer.setText("Update");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });
        add(btnUpdateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 220, 40));

        btnDeleteCustomer.setText("Delete");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });
        add(btnDeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 220, 40));

        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 220, 40));

        btnView1.setText("<<Export");
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });
        add(btnView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        Customer customer = getSelected();
        if (customer == null) {
            return;
        }
        this.parent.pushComponent(new PlaceOrUpdateOrderJpanel(salesPerson, customer));
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        CreateCustomerJPanel ccjp = new CreateCustomerJPanel(parent);
        parent.pushComponent(ccjp);
        
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        Customer customer = getSelected();
        UpdateCustomerJPanel ucjp = new UpdateCustomerJPanel(parent,customer);
        parent.pushComponent(ucjp);
        
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:
        Customer customer = getSelected();
        if (customer == null) {
            return;
        }
        customer.getMarket().removeElement(customer);
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:
        toCSV();
    }//GEN-LAST:event_btnView1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnView1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "Customer List";
    }

    @Override
    public JTable getTable() {
        return tblCustomer;
    }

    @Override
    public Object[] populateRow(Customer c) {
        return new Object[] {c, c.getId(), c.getMarket()};
    }

    @Override
    public void populateTable() {
        populateTable(Business.getInstance().getAllCustomers());
    }
}
