/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 
package UserInterface.SalesPerson.Customer;

import UserInterface.Components.HasTitle;
import UserInterface.Components.ParentUI;
import UserInterface.Components.TablePopulatable;
import biz.Components.Business;
import biz.Components.Customer;
import biz.Components.Market;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Administrator
 
public class SearchCustomerJPanel extends javax.swing.JPanel implements TablePopulatable<Customer>,HasTitle{

    /**
     * Creates new form SearchCustomerJPanel
     
    private ArrayList<Customer> customerList;
    private ParentUI parentUI;
    public SearchCustomerJPanel(ParentUI parentUI) {
        initComponents();
        this.customerList = Business.getInstance().getAllCustomers();
        this.parentUI = parentUI;
        populateMarket();
    }
    public void populateMarket(){
        marketCom.removeAllItems();
        for(Market ma : Business.getInstance().getMarketCatalog().getElementArrayList()){
            marketCom.addItem(ma);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        marketCom = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchT = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        nameTF.setText("  ");
        add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 80, -1));

        marketCom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(marketCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel1.setText("Please input customer's id you want:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 30));

        jLabel2.setText("Please choose a market first:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        searchT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "id", "Marketl"
            }
        ));
        jScrollPane1.setViewportView(searchT);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        if(nameTF.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please input anything!");
            return;
        }
        try {
            //        if(nameTF.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Please input a person");
//            return;
//        }
//        
//        for(Customer c : ma.elementArrayList){
//            if(c.getName().equals(nameTF.getText())){
//                customerList.add(c);
//            }
//        }
            Customer cust = ma.findCustomer(Integer.parseInt(nameTF.getText()));
            populateRow(cust);
        } catch (Market.Failed ex) {
            JOptionPane.showMessageDialog(this, "No such person");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox marketCom;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTable searchT;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTable getTable() {
        return searchT;
    }

    @Override
    public Object[] populateRow(Customer cu) {
        return new Object[]{cu , cu.getId(),cu.getMarket()};
    }

    @Override
    public void populateTable() {
        populateTable();
    }

    @Override
    public String getTitle() {
        return ("SearchCustomer");
    }
}
*/