/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss.Performance;

import UserInterface.Components.HasTitle;
import UserInterface.Components.ParentUI;

/**
 *
 * @author hezj
 */
public class PerformanceLandingPage extends javax.swing.JPanel implements HasTitle {
    private ParentUI parentUI;
    
    /**
     * Creates new form PerformanceLandingPage
     */
    public PerformanceLandingPage(ParentUI parentUI) {
        initComponents();
        this.parentUI = parentUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProductSalesRevenue = new javax.swing.JButton();
        btnTotalRevenue = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductSalesRevenue.setText("Product sales revenues by market >>");
        btnProductSalesRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductSalesRevenueActionPerformed(evt);
            }
        });
        add(btnProductSalesRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        btnTotalRevenue.setText("Total Revenue >>");
        btnTotalRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalRevenueActionPerformed(evt);
            }
        });
        add(btnTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jButton2.setText("Top 10 sales persons by revenues broken down by market >>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jButton3.setText("Sales persons above or below target sales >>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jButton5.setText("Top 3 products consistently sold above market target price >>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductSalesRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductSalesRevenueActionPerformed
        this.parentUI.pushComponent(new ProductSalesRevenueByMarket());
    }//GEN-LAST:event_btnProductSalesRevenueActionPerformed

    private void btnTotalRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalRevenueActionPerformed
        this.parentUI.pushComponent(new TotalRevenue());
    }//GEN-LAST:event_btnTotalRevenueActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.parentUI.pushComponent(new SalesPersonPerformance());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.parentUI.pushComponent(new ProductSoldAboveTargetPrice());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.parentUI.pushComponent(new TopSalesPersonInEachMarket());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductSalesRevenue;
    private javax.swing.JButton btnTotalRevenue;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "Choose what you wanna see.";
    }
}
