/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss.Performance;

import UserInterface.Components.HasTitle;
import UserInterface.Components.ParentUI;
import biz.Components.Business;
import biz.Components.Market;

/**
 *
 * @author royn
 */
public class TopSalesPersonInEachMarket extends javax.swing.JPanel implements HasTitle {
    private ParentUI parentUI;
    
    /**
     * Creates new form TopSalesPersonInEachMarket
     */
    public TopSalesPersonInEachMarket(ParentUI parentUI) {
        initComponents();
        this.parentUI = parentUI;
        
        cbMarket.removeAllItems();
        Business.getInstance().getMarketCatalog().getElementArrayList().forEach(m -> cbMarket.addItem(m)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMarket = new javax.swing.JComboBox();
        btnView = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbMarket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 160, -1));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        Market m = (Market) cbMarket.getSelectedItem();
        this.parentUI.pushComponent(new TopSalesPersonInEachMarketDetail(m));
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox cbMarket;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "Select Market to view its top 10 sales people";
    }
}
