/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss.Performance;

import UserInterface.Components.HasTitle;
import biz.Components.Business;

/**
 *
 * @author hezj
 */
public class TotalRevenue extends javax.swing.JPanel implements HasTitle {

    /**
     * Creates new form TotalRevenue
     */
    public TotalRevenue() {
        initComponents();
        this.txtTotalRevenue.setText(String.format("%.2f", Business.getInstance().getOrderDirectory().getTotalRevenue(true)));
        this.txtTotalRevenue2.setText(String.format("%.2f", Business.getInstance().getOrderDirectory().getTotalRevenue(false)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalRevenue = new javax.swing.JTextField();
        txtTotalRevenue2 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Expected Total Revenue (include drafted orders):");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel2.setText("Total Revenue (placed orders only):");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        txtTotalRevenue.setEnabled(false);
        add(txtTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 194, -1));

        txtTotalRevenue2.setEnabled(false);
        add(txtTotalRevenue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 200, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtTotalRevenue;
    private javax.swing.JTextField txtTotalRevenue2;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "Total revenue";
    }
}
