/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.network.university.college.Lecturer;

import biz.account.Account;
import biz.video.Video;
import javax.swing.JOptionPane;
import ui.components.HasTitle;

/**
 *
 * @author hezj
 */
public class AddOrEditVideo extends javax.swing.JPanel implements HasTitle {
    // TODO: VideoTag
    private Video video;
    private String title;
    private Account account;
    

    /**
     * Creates new form AddOrEditVideo
     */
    public AddOrEditVideo(Account account) {
        this(null, account);
    }
    
    public AddOrEditVideo(Video video, Account account) {
        initComponents();
        
        this.account = account;
        this.video = video;
        btn.setText(video == null ? "Add Video" : "Save Video");
        
        this.cbAdType.removeAllItems();
        this.cbAdType.addItem(Video.VideoAdType.AnyAdd);
        this.cbAdType.addItem(Video.VideoAdType.CommOnly);
        this.cbAdType.addItem(Video.VideoAdType.NoAdd);
        this.cbAdType.addItem(Video.VideoAdType.PSAOnly);
        
        if (video != null) {
            txtTitle.setText(video.getTitle());
            cbAdType.setSelectedItem(video.getTitle());
            txtDescription.setText(video.getDescription());
            txtPicPath.setText(video.getPicPath());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cbAdType = new javax.swing.JComboBox();
        btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPicPath = new javax.swing.JTextField();

        jLabel1.setText("Title");

        jLabel2.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jLabel3.setText("Ad Type");

        cbAdType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn.setText("btn");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Pic Path");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTitle)
                        .addComponent(cbAdType, 0, 208, Short.MAX_VALUE)
                        .addComponent(txtPicPath)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 792, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAdType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPicPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        String title = txtTitle.getText();
        String description = txtDescription.getText();
        String picPath = txtPicPath.getText();
        Video.VideoAdType type = (Video.VideoAdType) cbAdType.getSelectedItem();
        // TODO validation
        
        Video v;
        if (video == null) {
            v = account.getOrg().getEnterprise().getNetwork().getVideoCatalog().newVideo(account);
        } else {
            v = video;
        }
        v.setTitle(title);
        v.setDescription(description);
        v.setPicPath(picPath);
        v.setAdType(type);
        
        if (video == null) {
            txtTitle.setText("");
            txtDescription.setText("");
            txtPicPath.setText("");
            JOptionPane.showMessageDialog(this, "Added");
        } else {
            JOptionPane.showMessageDialog(this, "Saved");
        }
        
    }//GEN-LAST:event_btnActionPerformed

    @Override
    public String getTitle() {
        return video == null ? "Add Video" : "Edit Video";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JComboBox cbAdType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtPicPath;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
