/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson.Order;

import UserInterface.Components.HasTitle;
import UserInterface.Components.TablePopulatable;
import biz.Components.Customer;
import biz.Components.OfferProduct;
import biz.Components.Order;
import biz.Components.OrderProduct;
import biz.Components.SalesPerson;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hezj
 */
public class PlaceOrderJpanel extends javax.swing.JPanel implements HasTitle, TablePopulatable<OfferProduct> {
    private SalesPerson salesPerson;
    private Customer customer;
    private Order order;
    
    /**
     * Creates new form PlaceOrderJpanel
     */
    public PlaceOrderJpanel(SalesPerson salesPerson, Customer customer) {
        initComponents();
        this.salesPerson = salesPerson;
        this.customer = customer;
        
        // this.order = TODO: init order here
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductOffer = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderProduct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRevenue = new javax.swing.JTextField();
        btnPlaceOrder = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Supplier", "Lowest Price", "Target Price", "Highest Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductOffer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 888, 160));

        tblOrderProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Actual Unit Price", "Actual Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrderProduct);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 229, 888, 198));

        jLabel2.setText("Product Offer List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 194, 44, -1));

        jLabel3.setText("Quantity:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 199, -1, -1));

        jButton1.setText("Add To Order");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 194, -1, -1));

        jLabel1.setText("Total Price:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 438, -1, -1));

        txtTotalPrice.setEnabled(false);
        add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 433, 100, -1));

        jLabel4.setText("Revenue:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 476, -1, -1));
        add(txtRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 471, 100, -1));

        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 565, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        // set order status to placed
    }//GEN-LAST:event_btnPlaceOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblOrderProduct;
    private javax.swing.JTable tblProductOffer;
    private javax.swing.JTextField txtRevenue;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "Place Order";
    }

    @Override
    public JTable getTable() {
        return tblProductOffer;
    }

    @Override
    public Object[] populateRow(OfferProduct op) {
        return new Object[] {
            op,
            op.getProduct().getSupplier(),
            op.getLowestPrice(),
            op.getTargetPrice(),
            op.getHighestPrice(),
            op.getProduct().getStock()
        };
    }

    @Override
    public void populateTable() {
        populateTable(customer.getMarket().getMarketOffer().getElementArrayList());
    }
    
    public void populateOrder() {
        DefaultTableModel dtm = (DefaultTableModel) tblOrderProduct.getModel();
        dtm.setRowCount(0);

        for (OrderProduct op: order.getElementArrayList()) {
            dtm.addRow(new Object[] {
                op,
                op.getQuantity(),
                op.getActualPrice(),
                op.getTotalPrice()
            });           
        }
        
        txtTotalPrice.setText(Double.toString(order.totalPrice()));
        txtRevenue.setText(Double.toString(order.getRevenue()));
    }
}
