/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson.Order;

import UserInterface.Components.HasTitle;
import UserInterface.Components.TablePopulatable;
import biz.Components.Business;
import biz.Components.Customer;
import biz.Components.OfferProduct;
import biz.Components.Order;
import biz.Components.OrderProduct;
import biz.Components.SalesPerson;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author hezj
 */
public class PlaceOrUpdateOrderJpanel extends javax.swing.JPanel implements HasTitle, TablePopulatable<OfferProduct> {
    private SalesPerson salesPerson;
    private Customer customer;
    private Order order;

    /**
     * Creates new form PlaceOrderJpanel
     */
    public PlaceOrUpdateOrderJpanel(SalesPerson salesPerson, Customer customer) {
        initComponents();
        this.salesPerson = salesPerson;
        this.customer = customer;
        
        this.order = Business.getInstance().getOrderDirectory().newElement();
        this.order.setSoldBy(salesPerson);
        this.order.setBoughtBy(customer);
    }
    
    public PlaceOrUpdateOrderJpanel(Order order) {
        initComponents();
        this.salesPerson = order.getSoldBy();
        this.customer = order.getBoughtBy();
        
        this.btnPlaceOrder.setText("Save Order");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductOffer = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderProduct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRevenue = new javax.swing.JTextField();
        btnPlaceOrder = new javax.swing.JButton();
        txtActualPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnActualPrice = new javax.swing.JButton();
        btnQuantity = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtActualPrice2 = new javax.swing.JTextField();
        txtQuantity2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Supplier", "Lowest Price", "Target Price", "Highest Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductOffer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 888, 95));

        tblOrderProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Actual Unit Price", "Actual Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrderProduct);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 212, 888, 198));

        jLabel2.setText("Product Offer List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 177, 44, -1));

        jLabel3.setText("Quantity:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 182, -1, -1));

        btnAdd.setText("Add Selected To Order");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 177, -1, -1));

        jLabel1.setText("Total Price:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 421, -1, -1));

        txtTotalPrice.setEnabled(false);
        add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 416, 100, -1));

        jLabel4.setText("Revenue:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 456, -1, -1));
        add(txtRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 451, 100, -1));

        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, -1, -1));
        add(txtActualPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 177, 47, -1));

        jLabel5.setText("Actual Price:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 182, -1, -1));

        btnRemove.setText("Remove Selected From Order");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 416, -1, -1));

        btnActualPrice.setText("Go");
        btnActualPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualPriceActionPerformed(evt);
            }
        });
        add(btnActualPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 451, -1, -1));

        btnQuantity.setText("Go");
        btnQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantityActionPerformed(evt);
            }
        });
        add(btnQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 486, -1, -1));

        jLabel6.setText("ModifyS elected Actual Price to:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 456, -1, -1));
        add(txtActualPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 451, 90, -1));
        add(txtQuantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 486, 90, -1));

        jLabel7.setText("Modify Selected Quantity to:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 491, -1, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 6, -1, -1));

        jLabel8.setText("Find Product:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 147, -1, -1));
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 142, 88, -1));

        btnFind.setText("Go");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 142, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        this.order.setStatus("Placed");
        JOptionPane.showMessageDialog(this, "Order Placed");
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        OfferProduct offerProduct = getSelected();
        if (offerProduct == null) {
            return;
        }

        String actualPriceText = txtActualPrice.getText();
        double actualPrice;
        try {
            actualPrice = Double.parseDouble(actualPriceText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price.");
            return;
        }
        if (actualPrice > offerProduct.getHighestPrice()) {
            JOptionPane.showMessageDialog(this, "Price too high.");
            return;
        }
        if (actualPrice < offerProduct.getLowestPrice()) {
            JOptionPane.showMessageDialog(this, "Price too low.");
            return;
        }
        
        String quantityText = txtQuantity.getText();
        int quantity;
        try {
            quantity = Integer.parseInt(quantityText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity.");
            return;
        }
        if (quantity > offerProduct.getProduct().getStock()) {
            JOptionPane.showMessageDialog(this, "Not enough product in stock.");
            return;
        }

        offerProduct.getProduct().setStock(offerProduct.getProduct().getStock() - quantity);

        OrderProduct orderProduct = order.findElement(op -> op.getOfferProduct().equals(offerProduct));
        if (orderProduct != null) {
            orderProduct.setQuantity(orderProduct.getQuantity() + quantity);
        } else {
            orderProduct = order.newElement();
            orderProduct.setQuantity(quantity);
            orderProduct.setActualPrice(actualPrice);
            orderProduct.setOfferProduct(offerProduct);
        }
        populateOrder();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String productName = txtProductName.getText();
        ArrayList<OfferProduct> arr = customer.getMarket().getMarketOffer().findElements(op -> op.getProduct().getProductName().equals(productName));
        populateTable(arr);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        populateTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private OrderProduct getSelectedOrderProduct() {
        int selectedCount = tblOrderProduct.getSelectedRowCount();
        if (selectedCount > 1) {
            JOptionPane.showMessageDialog(this, "Please select no more than 1 row.");
            return null;
        }
        if (selectedCount < 1) {
            JOptionPane.showMessageDialog(this, "Please select 1 row.");
            return null;
        }

        return (OrderProduct) tblOrderProduct.getValueAt(tblOrderProduct.getSelectedRow(), 0);
    }

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        OrderProduct op = getSelectedOrderProduct();
        if (op == null) {
            return;
        }
        order.removeElement(op);
        populateOrder();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnActualPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualPriceActionPerformed
        OrderProduct orderProduct = getSelectedOrderProduct();
        if (orderProduct == null) {
            return;
        }
        
        String actualPriceTxt = txtActualPrice.getText();
        double actualPrice;
        try {
            actualPrice = Double.parseDouble(actualPriceTxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price.");
            return;
        }
        if (actualPrice > orderProduct.getOfferProduct().getHighestPrice()) {
            JOptionPane.showMessageDialog(this, "Price too high.");
            return;
        }
        if (actualPrice < orderProduct.getOfferProduct().getLowestPrice()) {
            JOptionPane.showMessageDialog(this, "Price too low.");
            return;
        }

        orderProduct.setActualPrice(actualPrice);
        populateOrder();
    }//GEN-LAST:event_btnActualPriceActionPerformed

    private void btnQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantityActionPerformed
        OrderProduct orderProduct = getSelectedOrderProduct();
        if (orderProduct == null) {
            return;
        }
        
        OfferProduct offerProduct = orderProduct.getOfferProduct();
        
        String quantityText = txtQuantity.getText();
        int quantity;
        try {
            quantity = Integer.parseInt(quantityText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity.");
            return;
        }
        if (quantity > offerProduct.getProduct().getStock()) {
            JOptionPane.showMessageDialog(this, "Not enough product in stock.");
            return;
        }
        
        orderProduct.setQuantity(orderProduct.getQuantity() + quantity);
        offerProduct.getProduct().setStock(offerProduct.getProduct().getStock() - quantity);
        populateOrder();
    }//GEN-LAST:event_btnQuantityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualPrice;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnQuantity;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrderProduct;
    private javax.swing.JTable tblProductOffer;
    private javax.swing.JTextField txtActualPrice;
    private javax.swing.JTextField txtActualPrice2;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantity2;
    private javax.swing.JTextField txtRevenue;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return String.format("Place Order for %s", customer);
    }

    @Override
    public JTable getTable() {
        return tblProductOffer;
    }

    @Override
    public Object[] populateRow(OfferProduct op) {
        return new Object[] {
            op,
            op.getProduct().getSupplier(),
            op.getLowestPrice(),
            op.getTargetPrice(),
            op.getHighestPrice(),
            op.getProduct().getStock()
        };
    }

    @Override
    public void populateTable() {
        populateTable(customer.getMarket().getMarketOffer().getElementArrayList());
    }
    
    public void populateOrder() {
        DefaultTableModel dtm = (DefaultTableModel) tblOrderProduct.getModel();
        dtm.setRowCount(0);

        for (OrderProduct op: order.getElementArrayList()) {
            dtm.addRow(new Object[] {
                op,
                op.getQuantity(),
                op.getActualPrice(),
                op.getTotalPrice()
            });           
        }
        
        txtTotalPrice.setText(Double.toString(order.totalPrice()));
        txtRevenue.setText(Double.toString(order.getRevenue()));
    }
}
