/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson.Order;

/**
 *
 * @author royn
 */
public class UpdateOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateOrderJPanel
     */
    public UpdateOrderJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtActualPrice = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxProduct = new javax.swing.JComboBox<>();
        cbxBoughtBy = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 110, 30));

        jLabel4.setText("Actual Price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, 30));

        jLabel5.setText("Order Product");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 110, 30));

        jLabel6.setText("Order Code");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, 30));
        add(txtActualPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 170, -1));
        add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 170, -1));
        add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 170, -1));

        jLabel7.setText("Bought By");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 110, 30));

        cbxProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbxProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 170, -1));

        cbxBoughtBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbxBoughtBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 170, -1));

        btnSave.setText("Save");
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 170, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxBoughtBy;
    private javax.swing.JComboBox<String> cbxProduct;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtActualPrice;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
