/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Boss.Order;

import UserInterface.Components.HasTitle;
import UserInterface.Components.ParentUI;
import UserInterface.Components.TablePopulatable;
import biz.Components.Order;
import biz.Components.OrderProduct;
import javax.swing.JTable;

/**
 *
 * @author hezj
 */
public class OrderDetailJPanel extends javax.swing.JPanel implements HasTitle, TablePopulatable<OrderProduct> {
    private ParentUI parent;
    private Order order;
    
    /**
     * Creates new form OrderDetailJPanel
     */
    public OrderDetailJPanel(ParentUI parent, Order order) {
        initComponents();
        this.parent = parent;
        this.order = order;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderProduct = new javax.swing.JTable();
        btnView1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrderProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Actual Price", "Revenue"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderProduct);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, -1));

        btnView1.setText("<<Export");
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });
        add(btnView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 170, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:
        toCSV();
    }//GEN-LAST:event_btnView1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrderProduct;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return String.format("Order Detail %s -> %s", order.getSoldBy(),  order.getBoughtBy());
    }

    @Override
    public JTable getTable() {
        return tblOrderProduct;
    }

    @Override
    public Object[] populateRow(OrderProduct orderProduct) {
        return new Object[] {
            orderProduct,
            orderProduct.getQuantity(),
            String.format("%.2f", orderProduct.getActualPrice()),
            String.format("%.2f", orderProduct.getTotalPrice()),
            String.format("%.2f", orderProduct.getReward()),
        };
    }

    @Override
    public void populateTable() {
        populateTable(order.getElementArrayList());
    }
}
